services:
  mistserver:
    image: ddvtech/mistserver_alpine_minimal
    container_name: mistserver
    volumes:
      - /PATH/TO/CONFIG/config.json:/config.json
      - /PATH/TO/VIDEOFOLDER:/video
    shm_size: 2gb
    network_mode: host
    restart: always
